In [ ]:
import numpy as np 


In [ ]:

#1-(10,15,30,45,60) degerlerine sahip numpy dizisi oluşturunuz
result=np.array([10,15,30,45,60])

In [ ]:
#2- 5 ve 15 arasındaki sayılarla numpy dizisi oluşturunuz

result=np.arange(5,15,1)
print(result)


[ 5  6  7  8  9 10 11 12 13 14]


In [ ]:
#3-(50-100) arasında 5 er 5 er artarak numpy dizisi oluşturunuz
result=np.arange(50,100,5)
print(result)

[50 55 60 65 70 75 80 85 90 95]


In [ ]:
#10 elemanlı birlerden oluşan bir dizi oluşturunuz 
result=np.array([])
for i in range(10):
    result=np.append(result,1)
 #VEYA 
sonuc=np.ones(10)

#0 lardan oluşan olsaydı 
sonuc=np.zeros(10)

In [ ]:
#0 ile 100 arasında eşit aralıklı 5 sayı üretin
result=np.linspace(0,100,5)

'''
arrange kullanmadık çünkü arrange tam olarak sayıları bölmüyor
(0,100) dediğimizde sayıları 99 da bırakıyor 
'''

rand 0 ile 1 arasında bir sayı üretir 

In [ ]:
result=np.random.randint(10,30,5)
print(result)


[20 11 15 22 15]


randn-> -1 iile 1 arasında sayı üretir

In [ ]:
result=np.random.randn(10)
print(result)


[ 0.17236934 -1.41655343  0.89019582  0.60156075 -0.96931161  0.30657473
  0.60537761 -0.45947411  0.15358552  0.22126229]


In [ ]:
#3x5 boyutlarında (10-50 arasında rastgele bir matris oluşturunuz)
result=np.random.randint(10,50,15).reshape(3,5)
print(result)

[[32 29 36 48 14]
 [35 37 27 49 49]
 [12 43 24 40 25]]


In [ ]:
#üretilen matrisin satır ve sütun sayılarını bul
matris=np.random.randint(10,50,15).reshape(3,5)
rowTotal=matris.sum(axis=1)
colTotal=matris.sum(axis=0)
print(rowTotal)
print(colTotal)


[153 182 109]
[ 88  73  79  99 105]


In [ ]:
#üretilen matrisin en büyük, en küçük ve ortalaması
matris=np.random.randint(10,50,15).reshape(3,5)
print(matris)
matrisMin=matris.min()
print(matrisMin)
matrisMax=matris.max()
print(matrisMax)
matrisOrt=matris.mean()
print(matrisOrt)

#üretilen metrisin en büyük değerinin indeksi
result=matris.argmax()
print(result)

#ilk satırı seçelim
a=matris[0]
print(a)




[[19 24 29 25 37]
 [30 16 29 26 44]
 [49 31 19 31 30]]
16
49
29.266666666666666
10
[19 24 29 25 37]


In [ ]:
arr=np.arange(10,20)
print(arr)
result=arr[:3]

[10 11 12 13 14 15 16 17 18 19]
